Feat/enable 3d heattrace
equinor/cc-components pull request #994
Opened 2024-04-29 10:03 UTC by MagnusGjosund

### Short summary

Implement/enable 3D for HT. 

Link to issue: https://github.com/equinor/cc-components/issues/942

### PR Checklist
- [ ] I have performed a self-review of my own code
- [ ] I have written a short summary of my changes in the PR
- [ ] I have linked related issue to the PR

> [!TIP]
> To deploy the PR to Test, use the [Manual deploy fusion app TEST🚀](https://github.com/equinor/cc-components/actions/workflows/manual-deploy.yml) action.
> Remember to deploy any backend changes to Test as well!

> [!CAUTION]
> ⛔ I understand by merging my PR, the changes will be deployed to production immediately ⛔

2024-04-29 10:08 UTC, Gustav-Eikaas commented
Remove .nx file and add to .gitignore plz

2024-05-08 06:47 UTC, kjellhaaland commented on libs/heattracesidesheet/src/lib/ui-sidesheet/HeattraceSidesheet.tsx
> +  const reszied = useRef({ hasResized: false, id: props.id });
We could consider deconstructing the props, so that we don't  needs to do props.xxx everywhere.

2024-05-08 06:48 UTC, kjellhaaland approved these changes

2024-05-13 07:35 UTC, Gustav-Eikaas requested changes

2024-05-13 07:35 UTC, Gustav-Eikaas commented on libs/heattracesidesheet/src/lib/utils-sidesheet/useGetEleNetwork.ts
> +    throw new Error(`Failed to resolve the heat trace`);
Failed to resolve what heat-trace? You shouldnt throw if heat-trace is null you should pause the query and resume it when the heat-trace is resolved..

2024-05-13 07:46 UTC, Gustav-Eikaas commented on libs/heattracesidesheet/src/lib/utils-sidesheet/useGetEleNetwork.ts
> +          ht.heatTraceCableNo
All the other resources for heat-trace seems to be using the `heatTraceCableId` field why is this one using the `heatTraceCableNo` field?

2024-05-13 07:47 UTC, Gustav-Eikaas commented on libs/heattracesidesheet/src/lib/utils-sidesheet/useGetEleNetwork.ts
> +    queryKey: [ht.heatTraceCableNo, ht.facility, ht.project],
QueryKey should contain info about which resource this is, e.g "echo". The way it is now it could cause a conflict in the future

2024-05-13 13:20 UTC, Gustav-Eikaas approved these changes

2024-05-13 13:38 UTC, merged